### ISSUE TITLE
app cannot be accessed from another host. 

### ISSUE THREAD

**Issue by romainguinot** [Alfresco/health-care-app#33] opened 2017-02-17 14:11 UTC
Alfresco 5.2 + Activiti 1.5.3 + healthcare app dev branch all running on the same host.

Using ADF 1.1.
npm 3.10.10 node v6.9.5, provided by Fedora 25.

Can be accessed from localhost on the same host. If trying to access the app from a VM or another host, OPTIONS request is failing 

> OPTIONS http://10.0.2.2:8080/alfresco/api/-default-/public/authentication/versions/1/tickets 403 (Interdit)
> ..
> login @ ecmAuth.js?b7bb:48
> _loginBPMECM @ alfrescoApi.js?6587:187
> login @ alfrescoApi.js?6587:154
> AlfrescoAuthenticationService.callApiLogin @ alfresco-authentication.service.ts?666c:68
> AlfrescoAuthenticationService.login @ alfresco-authentication.service.ts?666c:52
> AlfrescoLoginComponent.performeLogin @ alfresco-login.component.ts?b7d5:165
> AlfrescoLoginComponent.onSubmit @ alfresco-login.component.ts?b7d5:133
> View_AlfrescoLoginComponent0.handleEvent_4 @ /LoginModule/AlfrescoLoginComponent/component.ngfactory.js:661
> ..
> 

XHR request failing : 

> XMLHttpRequest cannot load http://10.0.2.2:8080/alfresco/api/-default-/public/authentication/versions/1/tickets. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.0.2.2:3000' is therefore not allowed access. The response had HTTP status code 403.

XHR request as CURL : 

> curl 'http://10.0.2.2:8080/alfresco/api/-default-/public/authentication/versions/1/tickets' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: http://10.0.2.2:3000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: fr,en;q=0.8,fr-FR;q=0.6,en-US;q=0.4' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://10.0.2.2:3000/login' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: authorization, content-type' --compressed

10.0.2.2 is the host IP from inside the virtualbox VM. Same issue accessing the app from another physical host.

result from the cURL on the windows guest OS (VM) : 

> G:>curl "http://10.0.2.2:8080/alfresco/api/-default-/public/authentication/versions/1/tickets" -X OPTIONS -H "Access-Control-Request-Method: POST" -H "Origin: http://10.0.2.2:3000" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: fr,en;q
> 0.8,fr-FR;q=0.6,en-US;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" -H "Accept: */*" -H "Referer: http://10.0.2.2:3000/login" -H "Connection: keep-alive" -H "Access-Con
> rol-Request-Headers: authorization, content-type" --compressed
> 
> Cross-Origin Resource Sharing (CORS) Filter: CORS origin denied
> 

App can log in fine if accessed from the host. 

Issue also occurs on a sample "yo" app using ADF 1.1 so it would seem to be a general framework issue that was never tested.... 

Also to note : 
in the CORS xml fragment in the jar that i've deployed in modules/platform, i have 

> 
>          <param-name>cors.allowOrigin</param-name>
>          <param-value>*</param-value>

The activiti config also has : 

> cors.allowed.origins=*

**Comment by wabson** [comment] 2017-02-17 17:48
I tried accessing my local development version here from inside a Windows environment hosted inside a VirtualBox container and the following command worked fine for me

```
C:\Users\WIll\Downloads>curl -v "http://10.0.2.2:8080/alfresco/api/-default-/public/authentication/versions/1/tickets" -X OPTIONS -H "Access-Control-Request-Method: POST" -H "Origin: http://10.0.2.2:3000" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: fr,en;q0.8,fr-FR;q=0.6,en-US;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64)AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" -H "Accept: /" -H "Referer: http://10.0.2.2:3000/login" -H "Connection: keep-alive" -H "Access-Conrol-Request-Headers: authorization, content-type" --compressed
* Trying 10.0.2.2...
* TCP_NODELAY set
* Connected to 10.0.2.2 (10.0.2.2) port 8080 (#0)
> OPTIONS /alfresco/api/-default-/public/authentication/versions/1/tickets HTTP/
1.1
> Host: 10.0.2.2:8080
> Access-Control-Request-Method: POST
> Origin: http://10.0.2.2:3000
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: fr,en;q0.8,fr-FR;q=0.6,en-US;q=0.4
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64)AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/56.0.2924.87 Safari/537.36
> Accept: /
> Referer: http://10.0.2.2:3000/login
> Connection: keep-alive
> Access-Conrol-Request-Headers: authorization, content-type
>
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Access-Control-Allow-Origin: http://10.0.2.2:3000
< Access-Control-Allow-Credentials: true
< Vary: Origin
< Access-Control-Max-Age: 3600
< Access-Control-Allow-Methods: HEAD, DELETE, POST, GET, OPTIONS, PUT
< Access-Control-Allow-Headers: Origin, Authorization, X-File-Type, Accept, X-File-Name, X-File-Size, Range, Content-Type
< Content-Length: 0
< Date: Fri, 17 Feb 2017 17:32:13 GMT
<
* Curl_http_done: called premature == 0
* Connection #0 to host 10.0.2.2 left intact
```

I was also able to run the ADF app successfully from within an instance of Chrome running within the guest OS and I was able to log in to the healthcare app.

So I'm afraid based on the provided instructions I'm not able to reproduce this.

**Comment by wabson** [comment] 2017-02-27 17:04
Closing this for now since I cannot reproduce, happy to re-open if there are some reproducible steps that work in another environment

**Closed by wabson** 2017-02-27 17:04 UTC
